balance_controller:
  virtual_model_controller:
    heading:
      kp: 2000
      kd: 500
      kff: 20
    lateral:
      kp: 2000
      kd: 1000
      kff: 0
    vertical:
      kp: 8000
      kd: 1000
      kff: 1
    roll:
      kp: 1000
      kd: 600
      kff: 0.2
    pitch:
      kp: 1000
      kd: 600
      kff: 0.2
    yaw:
      kp: 500
      kd: 350
      kff: 0.2
  contact_force_distribution:
    weights:
      force:
        heading: 1
        lateral: 1
        vertical: 1
      torque:
        roll: 1
        pitch: 1
        yaw: 1
      regularizer:
        value: 1
    constraints:
      friction_coefficient: 0.4
      minimal_normal_force: 5
