balance_controller:
  virtual_model_controller:
    heading:
      kp: 4000
      kd: 1000
      kff: 1000
    lateral:
      kp: 4000
      kd: 1000
      kff: 1000
    vertical:
      kp: 8000
      kd: 2000
      kff: 100
    roll:
      kp: 4000
      kd: 1000
      kff: 0.2
    pitch:
      kp: 3000
      kd: 1000
      kff: 0.2
    yaw:
      kp: 4000
      kd: 1000
      kff: 0.2
  contact_force_distribution:
    weights:
      force:
        heading: 1
        lateral: 1
        vertical: 1
      torque:
        roll: 1
        pitch: 1
        yaw: 1
      regularizer:
        value: 1
    constraints:
      friction_coefficient: 0.1
      minimal_normal_force: 10
