//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the balance_controller package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __balance_controller__BALANCE_CONTROLLERCONFIG_H__
#define __balance_controller__BALANCE_CONTROLLERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace balance_controller
{
  class balance_controllerConfigStatics;

  class balance_controllerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(balance_controllerConfig &config, const balance_controllerConfig &max, const balance_controllerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const balance_controllerConfig &config1, const balance_controllerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, balance_controllerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const balance_controllerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, balance_controllerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const balance_controllerConfig &config) const = 0;
      virtual void getValue(const balance_controllerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T balance_controllerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (balance_controllerConfig::* field);

      virtual void clamp(balance_controllerConfig &config, const balance_controllerConfig &max, const balance_controllerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const balance_controllerConfig &config1, const balance_controllerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, balance_controllerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const balance_controllerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, balance_controllerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const balance_controllerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const balance_controllerConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, balance_controllerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, balance_controllerConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<balance_controllerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(balance_controllerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("heading_kp"==(*_i)->name){heading_kp = boost::any_cast<double>(val);}
        if("heading_kd"==(*_i)->name){heading_kd = boost::any_cast<double>(val);}
        if("heading_kff"==(*_i)->name){heading_kff = boost::any_cast<double>(val);}
        if("lateral_kp"==(*_i)->name){lateral_kp = boost::any_cast<double>(val);}
        if("lateral_kd"==(*_i)->name){lateral_kd = boost::any_cast<double>(val);}
        if("lateral_kff"==(*_i)->name){lateral_kff = boost::any_cast<double>(val);}
        if("vertical_kp"==(*_i)->name){vertical_kp = boost::any_cast<double>(val);}
        if("vertical_kd"==(*_i)->name){vertical_kd = boost::any_cast<double>(val);}
        if("vertical_kff"==(*_i)->name){vertical_kff = boost::any_cast<double>(val);}
        if("roll_kp"==(*_i)->name){roll_kp = boost::any_cast<double>(val);}
        if("roll_kd"==(*_i)->name){roll_kd = boost::any_cast<double>(val);}
        if("roll_kff"==(*_i)->name){roll_kff = boost::any_cast<double>(val);}
        if("pitch_kp"==(*_i)->name){pitch_kp = boost::any_cast<double>(val);}
        if("pitch_kd"==(*_i)->name){pitch_kd = boost::any_cast<double>(val);}
        if("pitch_kff"==(*_i)->name){pitch_kff = boost::any_cast<double>(val);}
        if("yaw_kp"==(*_i)->name){yaw_kp = boost::any_cast<double>(val);}
        if("yaw_kd"==(*_i)->name){yaw_kd = boost::any_cast<double>(val);}
        if("yaw_kff"==(*_i)->name){yaw_kff = boost::any_cast<double>(val);}
        if("gravity_compensation_percentage"==(*_i)->name){gravity_compensation_percentage = boost::any_cast<double>(val);}
        if("x_dir_kp"==(*_i)->name){x_dir_kp = boost::any_cast<double>(val);}
        if("x_dir_kd"==(*_i)->name){x_dir_kd = boost::any_cast<double>(val);}
        if("y_dir_kp"==(*_i)->name){y_dir_kp = boost::any_cast<double>(val);}
        if("y_dir_kd"==(*_i)->name){y_dir_kd = boost::any_cast<double>(val);}
        if("z_dir_kp"==(*_i)->name){z_dir_kp = boost::any_cast<double>(val);}
        if("z_dir_kd"==(*_i)->name){z_dir_kd = boost::any_cast<double>(val);}
      }
    }

    double heading_kp;
double heading_kd;
double heading_kff;
double lateral_kp;
double lateral_kd;
double lateral_kff;
double vertical_kp;
double vertical_kd;
double vertical_kff;
double roll_kp;
double roll_kd;
double roll_kff;
double pitch_kp;
double pitch_kd;
double pitch_kff;
double yaw_kp;
double yaw_kd;
double yaw_kff;
double gravity_compensation_percentage;
double x_dir_kp;
double x_dir_kd;
double y_dir_kp;
double y_dir_kd;
double z_dir_kp;
double z_dir_kd;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double heading_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double heading_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double heading_kff;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lateral_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lateral_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lateral_kff;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vertical_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vertical_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vertical_kff;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_kff;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_kff;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_kff;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double gravity_compensation_percentage;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double x_dir_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double x_dir_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double y_dir_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double y_dir_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double z_dir_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double z_dir_kd;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("balance_controllerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const balance_controllerConfig &__max__ = __getMax__();
      const balance_controllerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const balance_controllerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const balance_controllerConfig &__getDefault__();
    static const balance_controllerConfig &__getMax__();
    static const balance_controllerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const balance_controllerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void balance_controllerConfig::ParamDescription<std::string>::clamp(balance_controllerConfig &config, const balance_controllerConfig &max, const balance_controllerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class balance_controllerConfigStatics
  {
    friend class balance_controllerConfig;

    balance_controllerConfigStatics()
    {
balance_controllerConfig::GroupDescription<balance_controllerConfig::DEFAULT, balance_controllerConfig> Default("Default", "", 0, 0, true, &balance_controllerConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.heading_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.heading_kp = 5000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.heading_kp = 300.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("heading_kp", "double", 0, "Proportional gain.", "", &balance_controllerConfig::heading_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("heading_kp", "double", 0, "Proportional gain.", "", &balance_controllerConfig::heading_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.heading_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.heading_kd = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.heading_kd = 40.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("heading_kd", "double", 0, "Derivative gain.", "", &balance_controllerConfig::heading_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("heading_kd", "double", 0, "Derivative gain.", "", &balance_controllerConfig::heading_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.heading_kff = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.heading_kff = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.heading_kff = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("heading_kff", "double", 0, "Feedforward gain.", "", &balance_controllerConfig::heading_kff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("heading_kff", "double", 0, "Feedforward gain.", "", &balance_controllerConfig::heading_kff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lateral_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lateral_kp = 5000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lateral_kp = 1200.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("lateral_kp", "double", 0, "Proportional gain.", "", &balance_controllerConfig::lateral_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("lateral_kp", "double", 0, "Proportional gain.", "", &balance_controllerConfig::lateral_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lateral_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lateral_kd = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lateral_kd = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("lateral_kd", "double", 0, "Derivative gain.", "", &balance_controllerConfig::lateral_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("lateral_kd", "double", 0, "Derivative gain.", "", &balance_controllerConfig::lateral_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lateral_kff = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lateral_kff = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lateral_kff = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("lateral_kff", "double", 0, "Feedforward gain.", "", &balance_controllerConfig::lateral_kff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("lateral_kff", "double", 0, "Feedforward gain.", "", &balance_controllerConfig::lateral_kff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vertical_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vertical_kp = 5000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vertical_kp = 1500.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("vertical_kp", "double", 0, "Proportional gain.", "", &balance_controllerConfig::vertical_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("vertical_kp", "double", 0, "Proportional gain.", "", &balance_controllerConfig::vertical_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vertical_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vertical_kd = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vertical_kd = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("vertical_kd", "double", 0, "Derivative gain.", "", &balance_controllerConfig::vertical_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("vertical_kd", "double", 0, "Derivative gain.", "", &balance_controllerConfig::vertical_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vertical_kff = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vertical_kff = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vertical_kff = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("vertical_kff", "double", 0, "Feedforward gain.", "", &balance_controllerConfig::vertical_kff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("vertical_kff", "double", 0, "Feedforward gain.", "", &balance_controllerConfig::vertical_kff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_kp = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_kp = 5000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_kp = 250.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("roll_kp", "double", 0, "Proportional gain.", "", &balance_controllerConfig::roll_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("roll_kp", "double", 0, "Proportional gain.", "", &balance_controllerConfig::roll_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_kd = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_kd = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("roll_kd", "double", 0, "Derivative gain.", "", &balance_controllerConfig::roll_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("roll_kd", "double", 0, "Derivative gain.", "", &balance_controllerConfig::roll_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_kff = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_kff = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_kff = 0.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("roll_kff", "double", 0, "Feedforward gain.", "", &balance_controllerConfig::roll_kff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("roll_kff", "double", 0, "Feedforward gain.", "", &balance_controllerConfig::roll_kff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_kp = 5000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_kp = 400.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("pitch_kp", "double", 0, "Proportional gain.", "", &balance_controllerConfig::pitch_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("pitch_kp", "double", 0, "Proportional gain.", "", &balance_controllerConfig::pitch_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_kd = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_kd = 80.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("pitch_kd", "double", 0, "Derivative gain.", "", &balance_controllerConfig::pitch_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("pitch_kd", "double", 0, "Derivative gain.", "", &balance_controllerConfig::pitch_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_kff = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_kff = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_kff = 0.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("pitch_kff", "double", 0, "Feedforward gain.", "", &balance_controllerConfig::pitch_kff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("pitch_kff", "double", 0, "Feedforward gain.", "", &balance_controllerConfig::pitch_kff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_kp = 5000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_kp = 200.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("yaw_kp", "double", 0, "Proportional gain.", "", &balance_controllerConfig::yaw_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("yaw_kp", "double", 0, "Proportional gain.", "", &balance_controllerConfig::yaw_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_kd = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_kd = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("yaw_kd", "double", 0, "Derivative gain.", "", &balance_controllerConfig::yaw_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("yaw_kd", "double", 0, "Derivative gain.", "", &balance_controllerConfig::yaw_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_kff = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_kff = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_kff = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("yaw_kff", "double", 0, "Feedforward gain.", "", &balance_controllerConfig::yaw_kff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("yaw_kff", "double", 0, "Feedforward gain.", "", &balance_controllerConfig::yaw_kff)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gravity_compensation_percentage = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gravity_compensation_percentage = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gravity_compensation_percentage = 1.08;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("gravity_compensation_percentage", "double", 0, "gravity compensation percentage", "", &balance_controllerConfig::gravity_compensation_percentage)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("gravity_compensation_percentage", "double", 0, "gravity compensation percentage", "", &balance_controllerConfig::gravity_compensation_percentage)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x_dir_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x_dir_kp = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x_dir_kp = 800.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("x_dir_kp", "double", 0, "single_leg_controller X kp.", "", &balance_controllerConfig::x_dir_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("x_dir_kp", "double", 0, "single_leg_controller X kp.", "", &balance_controllerConfig::x_dir_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x_dir_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x_dir_kd = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x_dir_kd = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("x_dir_kd", "double", 0, "single_leg_controller X kd.", "", &balance_controllerConfig::x_dir_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("x_dir_kd", "double", 0, "single_leg_controller X kd.", "", &balance_controllerConfig::x_dir_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.y_dir_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.y_dir_kp = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.y_dir_kp = 800.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("y_dir_kp", "double", 0, "single_leg_controller Y kp.", "", &balance_controllerConfig::y_dir_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("y_dir_kp", "double", 0, "single_leg_controller Y kp.", "", &balance_controllerConfig::y_dir_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.y_dir_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.y_dir_kd = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.y_dir_kd = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("y_dir_kd", "double", 0, "single_leg_controller Y kd.", "", &balance_controllerConfig::y_dir_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("y_dir_kd", "double", 0, "single_leg_controller Y kd.", "", &balance_controllerConfig::y_dir_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.z_dir_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.z_dir_kp = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.z_dir_kp = 800.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("z_dir_kp", "double", 0, "single_leg_controller Z kp.", "", &balance_controllerConfig::z_dir_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("z_dir_kp", "double", 0, "single_leg_controller Z kp.", "", &balance_controllerConfig::z_dir_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.z_dir_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.z_dir_kd = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.z_dir_kd = 80.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("z_dir_kd", "double", 0, "single_leg_controller Z kd.", "", &balance_controllerConfig::z_dir_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(balance_controllerConfig::AbstractParamDescriptionConstPtr(new balance_controllerConfig::ParamDescription<double>("z_dir_kd", "double", 0, "single_leg_controller Z kd.", "", &balance_controllerConfig::z_dir_kd)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(balance_controllerConfig::AbstractGroupDescriptionConstPtr(new balance_controllerConfig::GroupDescription<balance_controllerConfig::DEFAULT, balance_controllerConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<balance_controllerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<balance_controllerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<balance_controllerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    balance_controllerConfig __max__;
    balance_controllerConfig __min__;
    balance_controllerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const balance_controllerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static balance_controllerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &balance_controllerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const balance_controllerConfig &balance_controllerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const balance_controllerConfig &balance_controllerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const balance_controllerConfig &balance_controllerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<balance_controllerConfig::AbstractParamDescriptionConstPtr> &balance_controllerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<balance_controllerConfig::AbstractGroupDescriptionConstPtr> &balance_controllerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const balance_controllerConfigStatics *balance_controllerConfig::__get_statics__()
  {
    const static balance_controllerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = balance_controllerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __BALANCE_CONTROLLERRECONFIGURATOR_H__
